# Generated by Django 3.2.8 on 2021-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name="person's name")),
                ('password', models.CharField(max_length=32, verbose_name='password')),
            ],
        ),
    ]
