# Generated by Django 3.2.8 on 2021-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_usf',
            field=models.IntegerField(default=0, verbose_name='the image is userful or not'),
        ),
    ]
