# Generated by Django 3.2.4 on 2021-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_alter_image_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adapter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='is_released',
            field=models.IntegerField(default=0),
        ),
    ]
