# Generated by Django 3.2.4 on 2021-12-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_auto_20211128_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='labels',
            field=models.CharField(default='', max_length=100),
        ),
    ]
