# Generated by Django 3.2.4 on 2021-12-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='img_height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='img_width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
