# Generated by Django 3.2.4 on 2021-12-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20211218_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='tag',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
