# Generated by Django 3.2.4 on 2021-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_box_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_tagged',
            field=models.BooleanField(default=0),
        ),
    ]
