# Generated by Django 3.2.4 on 2021-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_image_is_tagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_tagged',
            field=models.IntegerField(default=0),
        ),
    ]
